### ISSUE TITLE
Criterio

### ISSUE THREAD

**Issue by cajubavictor** [amandafilizola/sortinghat#12]
Quais os critérios pra pertencer a cada casa ?

**Comment by amandafilizola** [comment]
# A Grifinória foi fundada por Godric Gryffindor.

Os selecionados para essa casa possuem muita bravura e coragem. A Grifinória é odiada pela casa Sonserina, de acordo com Fineus Nigellus Black, isso porque eles salvam a pele dos outros e não a de si mesmos. 
        "E quais eram as qualidades que definiem um grifinório?", e uma vozinha na cabeca de Harry respondeu: "a audácia, a coragem e o cavalherismo definem os grifinórios " 

```
   "Quem sabe sua morada é na Grifinória,
    casa onde habitam os corações indômitos.
    Ousadia, sangue-frio e nobreza  destacam os
    alunos da Grifinória dos demais."
```

# A Lufa-Lufa foi fundada por Helga Hufflepuff.

Os alunos da Lufa-Lufa prezam os que trabalham muito, os pacientes de mente e amigos leais e justos. Suas demandas são determinadas e, ao realizar um trabalho, dedica-se a ele com toda a sua força de vontade, criatividade e inteligência. Quando faz algo, é para ser o melhor - a determinação.

```
     "Quem sabe é na Lufa-Lufa que você vai morar,
      onde seus soldados são justos e leais, 
      pacientes, sinceros, sem medo da dor."
```

# A Corvinal foi fundada por Rowena Ravenclaw.

Acolhe os mais inteligentes dos alunos de Hogwarts. Os membros da Corvinal são inteligentes, perspicazes e bem humorados. Possuem uma grande sede de conhecimento, e pensam rápido na hora de dizer algo gracioso. Também pode ser percebido algum tipo de sensibilidade peculiar em cada um dos membros dessa casa. A Corvinal também tem fama de ter as meninas e garotos mais bonitos de toda a escola, mas talvez isso seja só coincidência ou mito. 

```
     "Quem sabe será a velha e sábia Corvinal
      A Casa dos que tem a mente sempre alerta
      Onde os homens de grande espírito e saber
      Sempre encontraram companheiros seus iguais."
```

# A Sonserina foi fundada por Salazar Slytherin.

Sonserinos são astutos e têm um enorme desejo de poder. São ambiciosos, capazes de usar quaisquer métodos para atingir seus objetivos. A maioria dos bruxos das trevas pertenceram a esta casa. Os sonserinos se orgulham do sangue puro. Os estudantes de puro-sangue são, na maioria das vezes, enviados a essa casa, mas isso não significa que só existem puro-sangues na casa. A Sonserina é por vezes associada ao mal, porém existem estudantes dessa casa bondosos. 

```
     "Ou quem sabe você pertence à Sonserina.
      E ali fará seus verdadeiros amigos.
      Homens de astúcia que usam quaisquer meios
      Para atingir os fins que antes colimaram."
```
